import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import SwordEffects from "../components/SwordCursor";
import FloatingShield from "../components/FloatingShield";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hexar",
  description: "Generated by create next app",
  icons: {
    icon: "/images/icons/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <SwordEffects /> */}
        {/* <div
  id="floating-shield-container"
  className="fixed inset-0 pointer-events-none z-[9999]"
>
  <img
  id="floating-shield"
  src="/images/icons/shield.png"
  className="absolute left-1/2 top-[15%] -translate-x-1/2 
             w-[120px] opacity-0 pointer-events-none 
             will-change-transform"
/>

</div> */}
        {/* <FloatingShield/> */}
        <Navbar/>
        
        {children}
        <Footer/>
      </body>
    </html>
  );
}
